### ISSUE TITLE
[Question]: Is it a middleware?

### ISSUE THREAD

**Issue by hffmnn** [fermyon/http-auth-middleware#20]
Hi,

thanks for this great example. 

I have one question though: Is it a "real" middleware? From my understanding a middleware can intercept requests and responses, but to me, it looks like this example only shows how to intercept the request.
Is it possible to also get a handle on the response or would this need another component after the `example` component?

**Comment by itowlson** [comment]
cc @michelleN @fibonacci1729

**Comment by fibonacci1729** [comment]
Hi @hffmnn !

Thanks for the great question and apologies for the delay!

For some context, this example was conceived to showcase composition in its earliest form. To call it a true "middleware" in the sense we are all familiar is a _little_ generous. In retrospect it would have been more appropriate to name this `http-auth-interceptor` (akin to interceptors in `grpc`).

As you mention real middlewares can intercept request / response bodies which is not currently possible without for example (as you suggest) appending a third component onto the chain to accept the response because of limitations with preview2 i/o in the component model and a lack of asyncness.
